import { render, screen, fireEvent, cleanup } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { CatalogoPage } from './CatalogoPage'
const mocks = vi.hoisted(() => ({ cargar: vi.fn(), buscar: vi.fn(), categoria: vi.fn() }))
vi.mock('../stores/authStore', () => ({ useAuthStore: () => ({ kiosco: { id: 'k1' } }) }))
vi.mock('../hooks/useTenantConfig', () => ({ useTenantConfig: () => ({ tieneEnvases: false, esFotocopiadora: false }) }))
vi.mock('../hooks/useProducts', () => ({ useProducts: () => ({ productos: [], categorias: [], cargando: false, busqueda: '', categoriaFiltro: null, setBusqueda: mocks.buscar, setCategoriaFiltro: mocks.categoria, cargarProductos: mocks.cargar, cargarCategorias: mocks.cargar }) }))
vi.mock('../stores/proveedorStore', () => ({ useProveedorStore: () => ({ proveedores: [], cargarProveedores: mocks.cargar }) }))
vi.mock('../components/catalogo/CategoryManager', () => ({ CategoryManager: () => null }))
vi.mock('../components/catalogo/ProductForm', () => ({ ProductForm: () => null }))
vi.mock('../components/catalogo/SiembraCatalogoModal', () => ({ SiembraCatalogoModal: () => null }))
vi.mock('../components/catalogo/AumentoPreciosModal', () => ({ AumentoPreciosModal: () => null }))
vi.mock('../components/catalogo/PreciosEnvasesModal', () => ({ PreciosEnvasesModal: () => null }))
vi.mock('../components/catalogo/EtiquetasGondolaModal', () => ({ EtiquetasGondolaModal: () => null }))
vi.mock('../components/catalogo/ImportarCatalogoModal', () => ({ ImportarCatalogoModal: () => null }))
afterEach(cleanup)
it('presenta indicadores, herramientas y ayudas del catálogo sin perder filtros', () => {
 render(<CatalogoPage />)
 expect(screen.getAllByRole('article')).toHaveLength(4)
 expect(screen.getByRole('heading', { name: 'Herramientas del catálogo' })).toBeTruthy()
 expect(screen.getByRole('combobox', { name: 'Filtrar por categoría' })).toBeTruthy()
 expect(screen.getByRole('combobox', { name: 'Filtrar por proveedor' })).toBeTruthy()
 expect(screen.getByText('No hay productos en el catálogo.')).toBeTruthy()
 const categorias = screen.getByRole('button', { name: /Gestionar Categorías/ })
 expect(categorias.getAttribute('aria-expanded')).toBe('false')
 fireEvent.click(categorias)
 expect(categorias.getAttribute('aria-expanded')).toBe('true')
 expect(screen.queryByRole('button', { name: 'Precios de Envases' })).toBeNull()
})
